### PR TITLE
Fix for putting summary in slide template

### PR DESCRIPTION
**Pull request by accorvin**
In my testing (note that Ralph hit the same issue), I hit an issue when rendering the template due to a
missing function "raw" for an issue. Upon further investigation, simply
accessing the "summary" field for the issue worked just fine.
    
It is curious that others have not hit this issue, so care should be
taken in ensuring that this change does not break others' use
cases/workflows.

### CODE REVIEW

**Comment by ashcrow** [comment]
@accorvin were you testing on Python 2 or 3?

**Comment by accorvin** [comment]
@ashcrow Python 2.7.10. Does it require Python 3?

**Comment by ashcrow** [comment]
@accorvin No, it doesn't require python 3 **but** I bet that's the issue. I'm going to guess that ``.raw`` may be part of the 3 library while the 2 library doesn't have that. I'll try to take a look and double check.

**Comment by ashcrow** [comment]
@accorvin Hrm. Looking at ``jira.Issue`` it does indeed have a ``raw`` field for both Python 2 and 3 of the library. I checked with 1.0.10 and 1.0.11. Can you confirm the version you are using?

**Comment by accorvin** [comment]
@ashcrow Yep, looks like I'm on 1.0.11.

Here's the output from my Pip freeze:
```
asn1crypto==0.24.0
beautifulsoup4==4.6.0
bs4==0.0.1
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
cryptography==2.1.4
defusedxml==0.5.0
docutils==0.14
enum34==1.1.6
html5lib==1.0.1
idna==2.6
ipaddress==1.0.19
Jinja2==2.10
jira==1.0.11
MarkupSafe==1.0
oauthlib==2.0.6
ordereddict==1.1
pbr==3.1.1
pycparser==2.18
pykerberos==1.2.1
requests==2.18.4
requests-kerberos==0.12.0
requests-oauthlib==0.8.0
requests-toolbelt==0.8.0
six==1.11.0
urllib3==1.22
webencodings==0.5.1
```

And I'm running the following command to get the issue:
```
 make -f Makefile.factory uploadstatus
```

**Comment by ashcrow** [comment]
It doesn't seem to break anything but give me a few. It seems odd that it stopped working all of the sudden.

**Comment by accorvin** [comment]
@ashcrow For what it's worth, the code (without my change) works just fine if I roll back to commit 6bd352c39b5f3574d80c35951da284879e752a43 so a change since then caused the problem. I haven't had a chance to identify which one yet.

**Comment by ashcrow** [comment]
Good info. I want to figure out why that specific template ends up needing to avoid ``raw``, but I don't see a reason to block this as it does fix the problem. I'll look more into it but will 👍 this PR.

**Comment by ashcrow** [comment]
I think it's due to b5eba1f858d78541323c3ff050a6c699a26c19dc after using good ol' ``tig``. Attempting to add the ``Issue`` instance itself caused a ``TypeError``. Adding it's fields didn't throw the exception and provided the needed information.

**Comment by accorvin** [comment]
Yeah, that looks like a very likely culprit.

**Comment by ashcrow** [comment]
To circle back back around, that is the change that removed ``raw`` from ``by_epic`` issues. 👍 to this PR as it's the proper change for said report.

**Pull request merged**
